parameters:
  hubdrop.github_username: "%app.github.username%"
  hubdrop.github_organization: "%app.github.organization%"
  hubdrop.github_authorization_key: "%app.github.authorization%"

  hubdrop.drupal_username: "%app.drupal.username%"
  hubdrop.drupal_password: "%app.drupal.password%"
  hubdrop.url: "%app.url%"
  hubdrop.repo_path: "%app.repo_path%"
  hubdrop.jenkins_url: "%app.jenkins_url%"
  hubdrop.jenkins_username: "%app.jenkins_username%"
  hubdrop.jenkins_password: "%app.jenkins_password%"
  hubdrop.paths.home: "/var/hubdrop"

services:
  hubdrop:
    class: HubDrop\Bundle\Service\HubDrop
    arguments: ["%hubdrop.github_username%", "%hubdrop.github_organization%", "%hubdrop.github_authorization_key%", "%hubdrop.drupal_username%", "%hubdrop.drupal_password%", "%hubdrop.url%", "%hubdrop.jenkins_url%", "%hubdrop.jenkins_username%", "%hubdrop.jenkins_password%", "%hubdrop.repo_path%", @router, @session]
