FROM jenkins:2.46.3

USER root

# ARG user=hubdrop
# ARG group=hubdrop

ARG NEW_UID=1000

RUN echo "Attempting to update jenkins UID to $NEW_UID ..."
RUN usermod -u $NEW_UID jenkins

RUN echo "Attempting to update jenkins GID to $NEW_UID ..."
RUN groupmod -g $NEW_UID jenkins

RUN echo "Attempting to change ownership of /var/jenkins_home to $NEW_UID ..."
RUN chown $NEW_UID /var/jenkins_home /usr/share/jenkins/ref -R
RUN chgrp $NEW_UID /var/jenkins_home /usr/share/jenkins/ref -R

USER jenkins